This User read response is to allow paymail server to address a specific user in the payd database
libsv/payd pull request #105
Opened 2022-01-10 13:31 UTC by sirdeggen

continued work will be necessary to be able to include user handle in the payment api. Once we have an invoice it's not necessary but the initial invoice creation will need a username.

2022-01-10 16:18 UTC, jadwahab commented on data/sqlite/migrations/1_initial.up.sql
> -    ,xprv       VARCHAR NOT NULL
we usually do the sql statement with the , at the beginning so that you can easily comment out lines - learnt that from the big dawg simon 😉

2022-01-10 16:20 UTC, jadwahab commented on data/sqlite/private_keys.go
> -	VALUES(:name, :xprv)
we don't wanna auto increment or something like that here?

2022-01-10 16:20 UTC, jadwahab commented on destinations.go
> +	Handle        null.String
what's the handle for?

2022-01-10 16:28 UTC, jadwahab requested changes
what's the  wallet_eg.db file for?

2022-01-10 16:47 UTC, sirdeggen commented on data/sqlite/migrations/1_initial.up.sql
> -    ,xprv       VARCHAR NOT NULL
Problem was that the comment at the top of the document was failing some validation so migration was failing. /* */ ==> --- instead.

Anyway - I used a plugin to auto format the document, I'll see if there's a setting you can use to ensure the commas are at the start.

2022-01-10 16:50 UTC, sirdeggen commented on data/sqlite/private_keys.go
> -	VALUES(:name, :xprv)
The idea here was that one user can have different aliases, and that those aliases can have different xprivs.

2022-01-10 16:51 UTC, sirdeggen commented on destinations.go
> +	Handle        null.String
optional ability to address a particular user within the service

2022-01-10 16:56 UTC, sirdeggen commented on invoices.go
> +	Handle null.String `json:"handle,omitempty" db:"handle,omitempty"`
I do not understand the purpose of the user table if we do not intend to support more than one user. 

Imagining replacing this with Electrum some day, it is likely that they will support multiple wallets within the same service. Whether you call this wallets or users or accounts is debatable but certainly more than one entity.

2022-01-10 16:57 UTC, sirdeggen commented on transports/http/routes.go
> +	RouteV1UserByHandle = "api/v1/user/:handle"
yes, great idea.

2022-01-11 12:56 UTC, Tigh-Gherr requested changes
Really good work so far.

A few things to call out here, also (I don't know how to comment this in the PR review lol), there's a file that looks to have been created `wallet_eg.db`, could that be deleted?

2022-01-11 12:56 UTC, Tigh-Gherr commented on data/sqlite/migrations/1_initial.up.sql
> +    ,s_owner BOOLEAN NOT NULL DEFAULT 0
This was originally called `is_owner`, I think the i was lost in a typo

2022-01-11 12:56 UTC, Tigh-Gherr commented on data/sqlite/migrations/1_initial.up.sql
> -    url                                 VARCHAR NOT NULL,
Is there a reason why the spacing of the data name and data type has been changed? Having it columned, while is a tad bit more work to maintain, makes for easier reading, and considering how read-only these files become I would say that the readibility is more important.

2022-01-11 12:56 UTC, Tigh-Gherr commented on data/sqlite/user.go
> +func (s *sqliteStore) Create(ctx context.Context, user payd.User) (sql.Result, error) {
Can these functions be renamed to include the datatype? So `CreateUser`, etc. Since the sqliteStore is also used for every datatype we have, (destinations, txs etc), we should be specific of the datatype to avoid naming collisions.

2022-01-11 12:56 UTC, Tigh-Gherr commented on data/sqlite/user.go
> +	`, user.Name, user.Avatar, user.Email, user.Address, user.PhoneNumber)
This code is highly vulnerable to SQL Injections, and should instead use a prepared statement.

Refer to creating an invoice for an example of how to do this:
https://github.com/libsv/payd/blob/master/data/sqlite/invoice.go#L15
https://github.com/libsv/payd/blob/master/data/sqlite/invoice.go#L71

2022-01-11 12:56 UTC, Tigh-Gherr commented on data/sqlite/user.go
> +	sqlGetUserIDFromHandle := fmt.Sprintf(`
SQL Injection possible throughout this function

2022-01-11 12:56 UTC, Tigh-Gherr commented on data/sqlite/user.go
> +	}
These 3 statements could be combined into a single one via joining. Something along the lines of
```
SELECT u.user_id, u.name, u.avatar_url, u.email, u.address, u.phone_number, k.xpriv FROM users u
JOIN keys k ON u.user_id = k.user_id
WHERE k.handle = :handle
```

You may need a custom datatype that is ready to receive user info and xpriv info, you could probably define the anonymous struct in line in this function

2022-01-11 12:56 UTC, Tigh-Gherr commented on docker-compose.local.yml
> +  volumes:
This re-indentation is not correct

2022-01-11 12:56 UTC, Tigh-Gherr commented on users.go
> +type UserStore interface {
Could this interface be updated to include the data type in the function signatures?

2022-01-11 14:24 UTC, sirdeggen commented on data/sqlite/migrations/1_initial.up.sql
> -    url                                 VARCHAR NOT NULL,
Just the result of an auto-format which I deeply regret. Will just revert and remake the file from og.

2022-01-13 13:13 UTC, Tigh-Gherr commented on transports/http/routes.go
> +	RouteV1Balance    = "api/v1/balance"
This file looks like it needs to be gofmt'd

2022-02-02 22:18 UTC, sirdeggen commented
@Tigh-Gherr I need your help resolving this conflict please.

The go.mod and vendor/modules.txt conflict are beyond my golang level. I don't want to kill anything which is working. I ran a `go mod tidy -go=1.16 && go mod tidy -go=1.17` which may have caused this discrepancy.

2022-02-02 22:24 UTC, Tigh-Gherr commented
Ye no worries ping me on slack

2022-02-03 13:28 UTC, Tigh-Gherr approved these changes
LGTM

2022-02-04 09:05 UTC, jadwahab commented on service/envelopes.go
> +	keyname := "masterkey"
should we add some `// TODO:` or something so that we can easily extend this in the future? we will definitely forget the reasonings and stuff from today about this decision and in the future will probably want to add in different users etc. @sirdeggen @Tigh-Gherr

2022-02-04 09:09 UTC, jadwahab approved these changes

2022-02-04 09:10 UTC, merged