Merkle Proofs via Peer Channels
libsv/payd pull request #109
Opened 2022-01-21 14:34 UTC by Tigh-Gherr

2022-01-22 13:07 UTC, jadwahab requested changes

2022-01-22 13:07 UTC, jadwahab commented on service/peerchannels_notify.go
> +	defer resp.Body.Close()
`Error return value of `resp.Body.Close` is not checked (errcheck)`

2022-01-22 13:07 UTC, jadwahab commented on service/peerchannels_notify.go
> +		defer sub.Conn.Close()
more linter errs `Error return value of `sub.Conn.Close` is not checked (errcheck)`

2022-01-22 13:07 UTC, jadwahab commented on service/peerchannels_notify.go
> +	if finished {
hmm does this close the channel directly after getting a merkle proof? what if there's more than 1 merkle proof? we should prolly keep the channel open for x time (like 2h or something set by config should be good enough for now)

2022-01-24 05:08 UTC, sirdeggen commented on service/payments.go
> +		Payment: &req,
I agree, and this was put forward in the invoice based payments TSC but the latest decree on that is to keep the current implementation as is until they confirm and them move forward with updating all the code, and then all the documentation. 😅

2022-01-24 09:52 UTC, jadwahab commented on service/payments.go
> +		Payment: &req,
even with the current implementation no one (that I've seen) returns the payment back in the paymentack 😅

2022-01-24 10:04 UTC, Tigh-Gherr commented on service/payments.go
> +		Payment: &req,
That's the first I've heard of payment being chopped, we've been doing it from day 0 lol. No worries tho I'll get rid of.

I like the new field with peer channel creds idea, I'll get on that.

2022-01-25 18:41 UTC, sirdeggen commented on cmd/internal/internal.go
> +		if err := deps.PeerChannelsNotifyService.Subscribe(ctx, &channel); err != nil {
When you loop through the range of channels, does it just reuse the same memory location to store each item as it runs the code within that block to save memory allocation resources?

If that's the case then I guess this failure is referring to the fact that the address being passed into the Subscribe function will always be the same address... in which case the value itself shoulid be passed rather than the address, otherwise depending on when it reads the data, the value would be different.

2022-01-25 20:38 UTC, sirdeggen commented on service/pay.go
> +		PeerChannelAccountID: 0,
Is this intentionally always set to 0, or ought this also to come from MerchantData?

2022-01-25 20:47 UTC, sirdeggen commented on service/proofs.go
> +		fmt.Printf("%#v\n", mm)
fmt.Printf Probably left here unintentionally?

2022-01-25 20:50 UTC, sirdeggen reviewed
I'm not going to pretend that I truly understand Peer Channels yet but this looks really good.
Just one fmt.Print seems out of place, and the looping over the slice and using the address rather than value to double check.

It took me so long to review that you may have already fixed that.

2022-01-26 11:43 UTC, Tigh-Gherr commented on service/pay.go
> +		PeerChannelAccountID: 0,
This is intentionally set to 0, as for this, 0 means a user that isn't us.

So, let's say I send a payment to you. You create a peer channel with your own peer channel creds, and you give me the channel id and an API key back.

For me to store these details, I don't have your peer channel creds in my database, so I've created a user id of `0` to account for all third part channels and api keys.

2022-01-26 11:43 UTC, Tigh-Gherr commented on service/proofs.go
> +		fmt.Printf("%#v\n", mm)
Haha it was

2022-02-04 09:16 UTC, jadwahab commented
@Tigh-Gherr some merge conflicts with deggen's user PR that we just merged

2022-02-10 17:11 UTC, jadwahab commented on config/defaults.go
> +	viper.SetDefault(EnvPeerChannelsTTL, 120)
that's 120 what, minutes?

2022-02-10 17:12 UTC, Tigh-Gherr commented on config/defaults.go
> +	viper.SetDefault(EnvPeerChannelsTTL, 120)
Yep! The env key specifies minutes, as `PEERCHANNELS_TTL_MINUTES`

2022-02-10 17:17 UTC, jadwahab approved these changes

2022-02-10 17:17 UTC, merged