Feature: Pay endpoint
libsv/payd pull request #36
Opened 2021-09-27 10:10 UTC by Tigh-Gherr

Assuming there are two instances of payd and p4 running, and one is funding, and an invoice exists on the receiver, you can call:

```
curl -H 'Content-Type: application/json' http://payd:8443/api/v1/pay -d '{
        "payToURL": "http://p4-merchant:28445/api/v1/payment/2JV7g4n"
}'
```

2021-09-27 13:08 UTC, theflyingcodr requested changes
Who needs comments 😛

2021-09-27 13:08 UTC, theflyingcodr commented on service/pay.go
> +			"https://" + p.svrCfg.Hostname + "/api/v1/proofs/" + spvEnvelope.TxID: {},
This should prob be a new config for P4 server or something like that.

2021-09-27 13:08 UTC, theflyingcodr commented on service/pay.go
> +func (p *pay) Pay(ctx context.Context, req payd.PayRequest) (*payd.PaymentACK, error) {
Comment this and also add a few comments through the function explaining the different sections, or split it up a wee bit.

2021-09-27 13:08 UTC, theflyingcodr commented on service/proofs.go
> +		wtr: rdrWtr,
why rename to rdrwtr if it's just a Writer?

2021-09-27 13:08 UTC, theflyingcodr commented on transaction.go
> +	TransactionChangeCreate(ctx context.Context, txArgs TransactionCreate, dArgs DestinationCreate) error
Anyway we could remove this and use the existing transactioncreate and destinationscreate calls?

2021-09-27 13:08 UTC, theflyingcodr commented on transports/http/pay.go
> +func (p *pay) RegisterRoutes(g *echo.Group) {
Comment this

2021-09-27 13:09 UTC, Tigh-Gherr commented on service/proofs.go
> +		wtr: rdrWtr,
Ah, it was a readerwriter at one point in development, missed that when changing it back

2021-09-27 13:10 UTC, Tigh-Gherr commented on transaction.go
> +	TransactionChangeCreate(ctx context.Context, txArgs TransactionCreate, dArgs DestinationCreate) error
Sure I'll take a look

2021-09-27 13:10 UTC, Tigh-Gherr commented on data/sqlite/transaction.go
> +func (s *sqliteStore) Tx(ctx context.Context, txID string) (*bt.Tx, error) {
This is so we conform to this interface https://github.com/libsv/go-bc/blob/master/spv/creator.go#L22

2021-09-27 13:11 UTC, Tigh-Gherr commented on data/sqlite/utxo.go
> +	SET reserved_for = $1, updated_at = DATETIME('now')
Good shout

2021-09-27 13:13 UTC, Tigh-Gherr commented on service/pay.go
> +			"https://" + p.svrCfg.Hostname + "/api/v1/proofs/" + spvEnvelope.TxID: {},
This is pointing at the payd server though.

Is the flow not: I give my callback url to the merchants P4, and then the merchant's p4 adds their own callback url to it?

2021-09-27 13:20 UTC, theflyingcodr commented on service/pay.go
> +			"https://" + p.svrCfg.Hostname + "/api/v1/proofs/" + spvEnvelope.TxID: {},
Ignore me again, this is fine yep

2021-09-27 17:09 UTC, Tigh-Gherr commented on transaction.go
> +	TransactionChangeCreate(ctx context.Context, txArgs TransactionCreate, dArgs DestinationCreate) error
Yep this worked

2021-09-28 11:56 UTC, theflyingcodr approved these changes
LGTM

2021-09-28 11:56 UTC, merged