Enhancement/mapi callback
libsv/payd pull request #6
Opened 2021-08-17 08:32 UTC by theflyingcodr

This adds support in for handling and storing a mapi call back, triggered when a new transaction is broadcast and received when a block is mined.

This falls in line with the SPV process and allows the wallet to store a proof for use in an SPV Envelope.

Also updated bt to v2 and tidied up some code.

2021-08-17 12:07 UTC, jadwahab requested changes
let's remove the regtest-stack stuff first

2021-08-17 12:07 UTC, jadwahab commented on proofs.go
> +		Validate("callbackPayload.proofType", func() error {
proofType can be nil (default case)

2021-08-17 15:27 UTC, theflyingcodr commented on proofs.go
> +		Validate("callbackPayload.proofType", func() error {
I have that catered for already 

```		
Validate("callbackPayload.proofType", func() error {
    if p.CallbackPayload.ProofType == "" {
    return nil
    }
```

2021-08-18 15:02 UTC, jadwahab approved these changes

2021-08-18 15:03 UTC, merged