Enhancement/socket transport
libsv/payd pull request #76
Opened 2021-11-15 14:34 UTC by theflyingcodr

This adds a socket transport to Payd to allow support for p2p wallet transactions via a p4 socket server.

Restructured a few of the services to work in the new transport, namely the pay service.

Removed some unit tests that are no longer relevant - will add these in another PR.

Lots of other tweaks.

2021-11-16 09:42 UTC, Tigh-Gherr requested changes
Really good work here.

Just a couple of things to point out.

2021-11-16 09:42 UTC, Tigh-Gherr commented on Dockerfile
> +RUN CGO_ENABLED=1 GOOS=linux go build -o server -ldflags="-s -w" ./cmd/$binary
Are the two binaries/containers necessary? It looks like it's introducing some management overhead which could be instead by handled by a switch on startup, either inferred from the P4_HOST's scheme, or even a new config variable.

2021-11-16 09:42 UTC, Tigh-Gherr commented on service/pay_test.go
> -			utxoReserveFunc: func() func(ctx context.Context, req payd.UTXOReserve) ([]payd.UTXO, error) {
Have these deleted test checks been brought over to the new envelopes service? I can't see them anywhere.

If not, the envelope service should include these tests.

2021-11-16 09:42 UTC, Tigh-Gherr commented on transports/sockets/middleware/middleware.go
> +	log.Error().Err(err).
nice

2021-11-16 10:02 UTC, theflyingcodr commented on cmd/rest-server/main.go
> +	services := internal.SetupRestDeps(cfg, log, db)
Yeah cleans up main a good bit, been meaning to do this for a while!

2021-11-16 10:05 UTC, theflyingcodr commented on service/pay_test.go
> -			utxoReserveFunc: func() func(ctx context.Context, req payd.UTXOReserve) ([]payd.UTXO, error) {
Nah they haven't yet, was just sprinting to get the thing done which require cut corners unfortunately.

2021-11-16 10:08 UTC, theflyingcodr commented on Dockerfile
> +RUN CGO_ENABLED=1 GOOS=linux go build -o server -ldflags="-s -w" ./cmd/$binary
I brought this in right at the start where I was of the opinion I'd have 2 distinct binaries, but as I've brought pretty much ALL the http endpoints into the socket one maybe a switch would be better.

THis is nice though as it means we can have a multi binary code base but each container only contains its own thing. So we could have libsv/payd-http - libsv/payd-socket - libsv/peer-channels in terms of images.

2021-11-16 10:10 UTC, theflyingcodr commented on data/sockets/pay_async.go
> +	parts := reURL.FindStringSubmatch(req.PayToURL)
I started with a pure golang approach that was kind of like the above, but I had to add validation etc in and regex was the clearest way imo anyway to achieve this.

2021-11-16 10:32 UTC, Tigh-Gherr commented on Dockerfile
> +RUN CGO_ENABLED=1 GOOS=linux go build -o server -ldflags="-s -w" ./cmd/$binary
Speaking strictly from a docker approach, a Dockerfile should be for a single image, not for multiple. Having multiple images produced from a single Dockerfile always introduces overhead and codebase specific knowledge for building.

For example, this change alone now means simple builds of our containers via `docker build -t "<container>:<image>" .` are broken.

If the functionalities are to be split into their own images, then I would say they should have their own Dockerfiles.

2021-11-16 10:33 UTC, Tigh-Gherr commented on data/sockets/pay_async.go
> +	parts := reURL.FindStringSubmatch(req.PayToURL)
I'm a "regex-in-production"-phobe lol, so I can't say I agree with this, but I won't block over it either.

2021-11-16 10:53 UTC, theflyingcodr commented on Dockerfile
> +RUN CGO_ENABLED=1 GOOS=linux go build -o server -ldflags="-s -w" ./cmd/$binary
Supplying args to containers is standard enough though, it would just need to be documented I think.

What I will do though is remove the 2nd binary, I think we could just use the one with a switch in the deps that are used and endpoints setup.

2021-11-16 10:53 UTC, theflyingcodr commented on service/pay_test.go
> -			utxoReserveFunc: func() func(ctx context.Context, req payd.UTXOReserve) ([]payd.UTXO, error) {
Once I finish documenting today I'll back fill these tests.

2021-11-16 10:54 UTC, Tigh-Gherr commented on Dockerfile
> +RUN CGO_ENABLED=1 GOOS=linux go build -o server -ldflags="-s -w" ./cmd/$binary
Also in regards to being two containers vs one with config, yep that's grand-o

2021-11-17 09:24 UTC, theflyingcodr commented on Dockerfile
> +RUN CGO_ENABLED=1 GOOS=linux go build -o server -ldflags="-s -w" ./cmd/$binary
Went with the single binary approach

2021-11-18 12:41 UTC, Tigh-Gherr approved these changes

2021-11-18 12:41 UTC, Tigh-Gherr commented
loookiinggg gooooooooooood

2021-11-19 10:01 UTC, merged